In [4]:
import torch
from torch import nn

In [12]:
#Dummy data
# Dummy input: 1 image, 3 channels (RGB), size 256x256
dummy_input0 = torch.randn(1, 3, 256, 256)  # Batch size = 1

In [13]:
#Build a model and print the data or shapes after each layer to understand the transformations
class SimpleCNN(nn.Module):
    def __init__(self, num_classes=2):
        super(SimpleCNN, self).__init__()
        self.conv1 = nn.Conv2d(3, 16, kernel_size=3, stride=1, padding=1)  # Conv Layer 1
        self.conv2 = nn.Conv2d(16, 32, kernel_size=3, stride=1, padding=1)  # Conv Layer 2
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)  # Max Pooling
        self.fc1 = nn.Linear(32 * 64 * 64, 128)  # Fully Connected Layer 1
        self.fc2 = nn.Linear(128, num_classes)  # Fully Connected Layer 2
        self.relu = nn.ReLU()  # Activation Function
        self.dropout = nn.Dropout(0.5)  # Dropout

    def forward(self, x):
        print(f"Input: {x.shape}\n{x}")  # Input
        x = self.pool(self.relu(self.conv1(x)))
        print(f"After Conv1 + ReLU + Pool: {x.shape}\n{x}")
        x = self.pool(self.relu(self.conv2(x)))
        print(f"After Conv2 + ReLU + Pool: {x.shape}\n{x}")
        x = x.view(x.size(0), -1)  # Flatten
        print(f"After Flatten: {x.shape}\n{x}")
        x = self.relu(self.fc1(x))
        print(f"After Fully Connected Layer 1: {x.shape}\n{x}")
        x = self.dropout(x)
        x = self.fc2(x)
        print(f"Output: {x.shape}\n{x}")
        return x


In [14]:
#Pass the dummy data input through the model and observe the outputs at each stage
# Create the model
model = SimpleCNN(num_classes=2)

# Pass dummy data through the model
output = model(dummy_input0)


Input: torch.Size([1, 3, 256, 256])
tensor([[[[ 0.3905,  1.0918, -0.0416,  ..., -0.6819,  1.8489,  0.4359],
          [-1.3359,  0.3841,  0.8309,  ..., -1.3491,  1.0997, -0.5703],
          [ 0.3508, -0.4144, -1.0023,  ...,  0.4300, -0.3547,  0.4341],
          ...,
          [-1.2627,  0.3310,  2.0278,  ..., -0.6218, -0.9481, -0.7911],
          [-1.1157, -0.3809, -2.0486,  ..., -0.9304, -0.5446, -1.0359],
          [ 1.2179, -0.1277,  0.5999,  ...,  0.8996,  1.0449,  0.0231]],

         [[ 0.6617,  0.6341,  0.4696,  ...,  0.3628, -2.2164,  1.3999],
          [-0.7924,  1.4935,  0.1135,  ...,  0.8745,  1.2956, -0.1897],
          [-0.3211,  0.0373, -1.1849,  ..., -0.7604, -1.4144, -0.9790],
          ...,
          [-1.1140,  0.6669,  1.2684,  ..., -0.9704,  0.4216,  0.4375],
          [ 0.3397,  1.2986, -0.2530,  ...,  0.7747,  0.1191,  0.4805],
          [-1.4590,  0.1391, -1.1187,  ...,  0.4303, -0.3499, -0.5822]],

         [[-0.7069, -0.6585,  0.1721,  ...,  0.5426,  1.0368, -0.0

Change the dummy data (e.g., vary the batch size, input size, or pixel values) to see how the model responds:

In [16]:
# Different batch sizes
dummy_input1 = torch.randn(4, 3, 256, 256)  # Batch size = 4

# Smaller image size
dummy_input2 = torch.randn(1, 3, 128, 128)  # Image size = 128x128

# Single-channel grayscale image
dummy_input3 = torch.randn(1, 1, 256, 256)  # Channels = 1


In [17]:
# Pass dummy data through the model
output = model(dummy_input1)

Input: torch.Size([4, 3, 256, 256])
tensor([[[[-3.1367e-01, -1.8515e+00, -2.8863e-01,  ...,  5.5595e-01,
           -3.1906e-01, -5.8132e-01],
          [-5.6503e-01, -9.7106e-01, -2.0598e-02,  ...,  3.2778e-02,
            1.0398e-01, -1.4648e+00],
          [-4.4033e-01, -4.9387e-01, -4.9054e-01,  ..., -9.4239e-01,
            5.7094e-02,  2.5032e-01],
          ...,
          [ 2.0153e+00,  3.5074e+00,  2.0420e+00,  ...,  7.9431e-01,
            2.7423e-02, -3.4658e-01],
          [-5.2008e-01,  2.4003e-01,  1.8613e+00,  ...,  3.9293e-01,
            9.5780e-01, -8.2715e-01],
          [-1.1721e+00, -2.6996e+00, -3.7182e-01,  ..., -2.7102e-01,
            6.2250e-01,  6.2415e-01]],

         [[-1.0841e+00,  5.9021e-01,  4.1470e-01,  ...,  5.7037e-01,
           -5.2923e-02, -2.0316e+00],
          [ 2.2389e+00, -4.5071e-01, -3.1647e-01,  ...,  2.0271e-01,
            4.9887e-01,  6.8538e-01],
          [-5.4414e-02, -1.4757e+00, -2.3712e-01,  ...,  4.2399e-01,
           -3.8349e-01

In [18]:
output = model(dummy_input2)

Input: torch.Size([1, 3, 128, 128])
tensor([[[[ 0.8501,  1.0797, -0.8210,  ...,  0.5213, -0.2416, -0.3745],
          [-0.8800, -1.1201,  1.0799,  ..., -0.3710, -1.0241, -0.6462],
          [ 0.8250, -0.0806, -0.6301,  ...,  1.3683,  0.4165, -0.1465],
          ...,
          [-1.1595, -0.8111, -0.7829,  ..., -1.8491,  0.8054,  1.6433],
          [ 0.1269, -0.9951,  0.4788,  ...,  1.5592, -0.1432, -0.8466],
          [-0.7765,  1.0584, -0.0738,  ...,  0.9303, -2.2435,  0.0516]],

         [[ 0.8612,  0.2330,  0.3774,  ...,  1.5917, -0.7718,  0.0821],
          [ 0.5168, -0.9616,  1.4211,  ..., -0.1938,  0.6432, -1.0649],
          [-0.7384,  1.2451, -0.9080,  ...,  0.6415, -1.6393, -1.4216],
          ...,
          [-0.4991,  0.8696, -2.1460,  ...,  0.5937,  0.2029,  0.5020],
          [ 0.0724,  0.4575, -0.8392,  ...,  0.7401,  1.2802, -0.1567],
          [-0.6952,  0.2268, -0.5240,  ...,  0.5163,  0.2630, -1.0362]],

         [[-1.5628, -0.5655,  0.5406,  ..., -0.0203, -2.0353, -0.1

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x32768 and 131072x128)

In [ ]:
output = model(dummy_input3)